"""test_readme_example_in_sync.py — README.md's bevo-copytrade worked
example is generated by scripts/sync_readme.py from the real
skills/bevo-copytrade/{SKILL.md,duty.py}. This test fails CI if the
generated block in README.md has drifted from those files (or if someone
edited the generated block by hand instead of the source files)."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / "README.md"
SYNC_SCRIPT = REPO_ROOT / "scripts" / "sync_readme.py"
SKILL_MD_PATH = REPO_ROOT / "skills" / "bevo-copytrade" / "SKILL.md"
DUTY_PY_PATH = REPO_ROOT / "skills" / "bevo-copytrade" / "duty.py"

BEGIN_MARKER = "<!-- BEGIN GENERATED: bevo-copytrade worked example (scripts/sync_readme.py; do not edit by hand) -->"
END_MARKER = "<!-- END GENERATED: bevo-copytrade worked example -->"


def extract_generated_block(readme_text: str) -> str:
    before, rest = readme_text.split(BEGIN_MARKER, 1)
    block, _after = rest.split(END_MARKER, 1)
    return block


def test_readme_has_generated_markers():
    text = README_PATH.read_text()
    assert BEGIN_MARKER in text
    assert END_MARKER in text


def test_sync_readme_check_passes_on_current_tree():
    proc = subprocess.run(
        [sys.executable, str(SYNC_SCRIPT), "--check"],
        capture_output=True, text=True, cwd=str(REPO_ROOT),
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_readme_block_matches_source_files_byte_for_byte():
    readme_text = README_PATH.read_text()
    block = extract_generated_block(readme_text)

    skill_md = SKILL_MD_PATH.read_text().rstrip("\n")
    duty_py = DUTY_PY_PATH.read_text().rstrip("\n")

    assert skill_md in block, "README's generated block does not contain the exact SKILL.md contents"
    assert duty_py in block, "README's generated block does not contain the exact duty.py contents"


def test_no_zero_width_space_anywhere_in_readme():
    text = README_PATH.read_text()
    assert "\u200b" not in text
