"""test_readme_example_in_sync.py — README.md's butler-copytrade worked
example is generated by scripts/sync_readme.py from butler-copytrade's own
repository, cloned at the ref skills.json follows (nothing is checked out
here). This test fails CI if the generated block in README.md has drifted
from that checkout — because someone edited the block by hand instead of
regenerating it, or because the skill repo has moved since it was last
generated. The clone comes from the session-scoped `copytrade_checkout`
fixture (tests/conftest.py), so these are skipped, not failed, offline."""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / "README.md"
SYNC_SCRIPT = REPO_ROOT / "scripts" / "sync_readme.py"

BEGIN_MARKER = "<!-- BEGIN GENERATED: butler-copytrade worked example (scripts/sync_readme.py; do not edit by hand) -->"
END_MARKER = "<!-- END GENERATED: butler-copytrade worked example -->"


def extract_generated_block(readme_text: str) -> str:
    before, rest = readme_text.split(BEGIN_MARKER, 1)
    block, _after = rest.split(END_MARKER, 1)
    return block


def test_readme_has_generated_markers():
    text = README_PATH.read_text()
    assert BEGIN_MARKER in text
    assert END_MARKER in text


def test_sync_readme_check_passes_on_current_tree(copytrade_checkout):
    proc = subprocess.run(
        [sys.executable, str(SYNC_SCRIPT), "--check"],
        capture_output=True, text=True, cwd=str(REPO_ROOT),
    )
    assert proc.returncode == 0, proc.stdout + proc.stderr


def test_readme_block_matches_source_files_byte_for_byte(copytrade_checkout):
    readme_text = README_PATH.read_text()
    block = extract_generated_block(readme_text)

    skill_md = (copytrade_checkout / "SKILL.md").read_text().rstrip("\n")
    duty_py = (copytrade_checkout / "duty.py").read_text().rstrip("\n")

    assert skill_md in block, "README's generated block does not contain the exact SKILL.md contents"
    assert duty_py in block, "README's generated block does not contain the exact duty.py contents"


def test_no_zero_width_space_anywhere_in_readme():
    text = README_PATH.read_text()
    assert "\u200b" not in text
